### ISSUE TITLE
Update Helm API to v2

### ISSUE THREAD

**Issue by salvis2** [yuvipanda/hubploy-template#3]
Do we want to change to API v2? It would consolidate `requirements.yaml` into `Chart.yaml`, and that should be fine now that Helm 3 is supported. I'm not sure if that will cause problems for people using Helm 2.

**Comment by consideRatio** [comment]
Helm 3 can parse Chart.yaml with apiVersion: v1 or v2, while Helm 2 can only parse Chart.yaml with apiVersion: v1.

So if this template updates a Chart.yaml to use apiVersion: v2, it will force the use of helm3 to install the chart.
