### ISSUE TITLE
Helm 3 unsupported according to README.rst

### ISSUE THREAD

**Issue by consideRatio** [yuvipanda/hubploy-template#5]
> A local install of helm 2. Note that helm 3 is not supported yet. The client version should match the version on your server (you can find your server version with helm version.

It seems though that hubploy now support the use of helm3, because it use a common API and actively checks for a namespace to be available etc.

**Comment by salvis2** [comment]
This repo is pretty out-of-date. I'm probably going to target it for some overhaul this week.
